@url = https://localhost:5001/api
@token = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkB0ZXN0LmNvbSIsImdpdmVuX25hbWUiOiJCb2IiLCJuYmYiOjE2MTU5MzI0MjEsImV4cCI6MTYxNjUzNzIyMSwiaWF0IjoxNjE1OTMyNDIxLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIn0.TBg0Nx8SghJ2b4Ywi7xWR7axAawcTTD8uP5EbgazeR-nC_NhY2Y2B4IIMUPZdkTltfb-XuNdcUS4sSF2KcItwQ

##################################################################
### ACCOUNT
##################################################################
### GET account
GET {{url}}/account
Content-Type: application/json
Authorization: {{token}}

### GET account
GET {{url}}/account/emailexists?email=bob@test.com
Content-Type: application/json

### GET account
GET {{url}}/account/address
Content-Type: application/json
Authorization: {{token}}

### PUT address
PUT {{url}}/account/address
Content-Type: application/json
Authorization: {{token}}

{
  "firstName": "Bob",
  "lastName": "Bobbity",
  "street": "12 The street",
  "city": "New York",
  "state": "NY",
  "zipCode": "90212"
}

### POST login
POST {{url}}/account/login
Content-Type: application/json

{
  "email": "bob@test.com",
  "password": "Pa$$w0rd"
}

### POST register
POST {{url}}/account/register
Content-Type: application/json

{
  "displayName": "test02",
  "email": "test02@test.com",
  "password": "Pa$$w0rd02"
}

##################################################################
### PRODUCTS
##################################################################

### GET products
GET {{url}}/products?Search=purple

### GET product
@productId = 1
GET {{url}}/products/{{productId}}

### GET brands
GET {{url}}/products/brands


### GET types
GET {{url}}/products/types


##################################################################
### BASKET
##################################################################

### get basket
GET {{url}}/basket/?id=1

### update basket
POST {{url}}/basket
Content-Type: application/json

{
  "id": "1",
  "items": [
    {
        "id":1,
        "productName": "Samsung Galaxy 10",
        "price": 10,
        "quantity": 1,
        "brand": "Samsung",
        "type": "smartphone"

    }
  ]
}


### delete basket
DELETE {{url}}/basket/?id=1