@url = https://localhost:5001/api
@token = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkB0ZXN0LmNvbSIsImdpdmVuX25hbWUiOiJCb2IiLCJuYmYiOjE2NDE2NTM2MzAsImV4cCI6MTY0MjI1ODQzMCwiaWF0IjoxNjQxNjUzNjMwLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIn0.nTW0MVu9W9LM-9f743jOVexE-wwv8PE9-mEMwss_urtgCHR5-yC0rf6I7YcYVbVFdfVqpZuFNhijR3RrL341AA

##################################################################
### ACCOUNT
##################################################################
### GET account
GET {{url}}/account
Content-Type: application/json
Authorization: {{token}}

### GET account
GET {{url}}/account/emailexists?email=bob@test.com
Content-Type: application/json

### GET account
GET {{url}}/account/address
Content-Type: application/json
Authorization: {{token}}

### PUT address
PUT {{url}}/account/address
Content-Type: application/json
Authorization: {{token}}

{
  "firstName": "Bob",
  "lastName": "Bobbity",
  "street": "12 The street",
  "city": "New York",
  "state": "NY",
  "zipCode": "90212"
}

### POST login
POST {{url}}/account/login
Content-Type: application/json

{
  "email": "bob@test.com",
  "password": "Pa$$w0rd"
}

### POST register
POST {{url}}/account/register
Content-Type: application/json

{
  "displayName": "test03",
  "email": "test03@test.com",
  "password": "Pa$$w0rd03"
}

##################################################################
### PRODUCTS
##################################################################

### GET products
GET {{url}}/products?Search=purple

### GET product
@productId = 1
GET {{url}}/products/{{productId}}

### GET brands
GET {{url}}/products/brands


### GET types
GET {{url}}/products/types


##################################################################
### BASKET
##################################################################

### get basket
GET {{url}}/basket/?id=1

### update basket
POST {{url}}/basket
Content-Type: application/json

{
  "id": "1",
  "items": [
    {
        "id":17,
        "productName": "Angular Magic Boots",
        "price": 1,
        "quantity": 20,
        "pictureUrl": "https://localhost:5001/images/products/boot-ang2.png",
        "brand": "Angular",
        "type": "Boots"

    }
  ]
}


### delete basket
DELETE {{url}}/basket/?id=1

##################################################################
### ORDERS
##################################################################
### get orders
GET {{url}}/orders
Content-Type: application/json
Authorization: {{token}}


### get order
GET {{url}}/orders/1
Content-Type: application/json
Authorization: {{token}}

### get delivery methods
GET {{url}}/orders/deliverymethods
Content-Type: application/json
Authorization: {{token}}

### create order
POST {{url}}/orders
Content-Type: application/json
Authorization: {{token}}

{
  "basketId": "1",
  "deliveryMethodId": 2,
  "shipToAddress":
  {
    "firstName": "Bob",
    "lastName": "Bobbity",
    "street": "10 The Street",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "zipcode": "90250"
  } 
}